export const REGISTER_ITEM_CONSTANTS = 'REGISTER_ITEM_CONSTANTS'
export const REGISTER_LOADING_CONSTANTS = 'REGISTER_LOADING_CONSTANTS'
export const REGISTER_ERROR_CONSTANTS = 'REGISTER_ERROR_CONSTANTS'

export const LOGIN_ITEM_CONSTANTS = 'LOGIN_ITEM_CONSTANTS'
export const LOGIN_LOADING_CONSTANTS = 'LOGIN_LOADING_CONSTANTS'
export const LOGIN_ERROR_CONSTANTS = 'LOGIN_ERROR_CONSTANTS'

export const USER_ITEM_CONSTANTS = 'USER_ITEM_CONSTANTS'
export const USER_LOADING_CONSTANTS = 'USER_LOADING_CONSTANTS'
export const USER_ERROR_CONSTANTS = 'USER_ERROR_CONSTANTS'

export const FORGOT_PASSWORD_CONTANTS = 'FORGOT_PASSWORD_CONTANTS'
export const FORGOT_PASSWORD_LOADING_CONSTANTS = 'FORGOT_PASSWORD_LOADING_CONSTANTS'
export const FORGOT_PASSWORD_ERROR_CONSTANTS = 'FORGOT_PASSWORD_ERROR_CONSTANTS'

export const RESET_PASSWORD_ERROR_CONSTANTS = 'RESET_PASSWORD_ERROR_CONSTANTS'
export const RESET_PASSWORD_LOADING_CONSTANTS = 'RESET_PASSWORD_LOADING_CONSTANTS'
export const RESET_PASSWORD_SUCCESS_CONSTANTS = 'RESET_PASSWORD_SUCCESS_CONSTANTS'