export const REGISTER_ITEM_CONSTANTS = 'REGISTER_ITEM_CONSTANTS'
export const REGISTER_LOADING_CONSTANTS = 'REGISTER_LOADING_CONSTANTS'
export const REGISTER_ERROR_CONSTANTS = 'REGISTER_ERROR_CONSTANTS'

export const LOGIN_ITEM_CONSTANTS = 'LOGIN_ITEM_CONSTANTS'
export const LOGIN_LOADING_CONSTANTS = 'LOGIN_LOADING_CONSTANTS'
export const LOGIN_ERROR_CONSTANTS = 'LOGIN_ERROR_CONSTANTS'