export const REGISTER_ITEM_CONSTANTS = 'REGISTER_ITEM_CONSTANTS'
export const REGISTER_LOADING_CONSTANTS = 'REGISTER_LOADING_CONSTANTS'
export const REGISTER_ERROR_CONSTANTS = 'REGISTER_ERROR_CONSTANTS'